# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ab1abc07e962a320b3a1feecc52cbcdec441172709419bfe0a2663738ff310a2a976fb01206954a97cdc838483cfe912ebccdf95ee281b6f17ec4be5b758d79

test:
  secret_key_base: f83d58c24111f81e4ffc2ded2f47c0ca1d955001e4c618823ec996a9984a2c6681af5a2e947f15c1c50d36c470e19f81b630c76b7af3d0e7cf3c77be25c31dd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
